### ISSUE TITLE
Command for individual stats

### ISSUE THREAD

**Issue by nch0w** [nch0w/tourney-bot#2]
E.g. `s!stats {username}`. Would return winrates (wins/losses), total points, and include replay links to the games. Could be formatted similarly to the schedule embed. 

In the future, we would want to use the global spreadsheet so people can see their stats across all tourneys.

**Comment by sadnixon** [comment]
Pretty much done. Implemented winrates, total points, and stats from the global sheet. Only thing missing is replay links... May add in the future, but would be tricky for historic games (esp since 3rd tourney does not have real workable replays)
